# This is a basic workflow to run tests in OpenFOAM v2206 containers
name: OF2206

# Make sure shells are interactive, so OF can get sourced
defaults:
  run:
    shell: bash -o pipefail -i {0}

# Controls when the workflow will run
on:
  push

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: ghcr.io/foamscience/jammy-openfoam:v2206
      options: --cpus 2 --user openfoam
      env:
        CATCH_TIMEOUT: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile and Test
        run: |
          source /usr/lib/openfoam/openfoam2206/etc/bashrc
          mkdir -p $FOAM_USER_LIBBIN
          sed -i 's/mpirun/mpirun --oversubscribe/g' Alltest
          ./Alltest
